### PR TITLE
Mount tools dir into job container

### PR DESCRIPTION
**Pull request by nuwang**

### CODE REVIEW

**Comment by pcm32** [comment]
Why don't we simply copy to the PVC (as you are doing) and change the galaxy config pointing to the location on the PVC where this is copied, instead of mingling with the PVC mountpoints for the jobs?

**Comment by pcm32** [comment]
or jobs are currently not mounting the entire galaxy PVC?

**Comment by nuwang** [comment]
@pcm32 That's a good idea. Let me try that.

**Comment by nuwang** [comment]
@pcm32 You mean like this? I wish we had a way to specify subpaths when mounting containers, in fact, I could have sworn that was added, but looking at the code now, I don't see that option anymore.

**Comment by pcm32** [comment]
Yep, plus reverting 171 and 180 of the configs.

**Comment by nuwang** [comment]
@pcm32 Thanks. I'll test this out and make sure everything's working.

**Pull request merged**
