### PR TITLE
Remove CVMFS fix

### LINKED ISSUE #439: Crashes without Refdata on CVMFS
I currently try to deploy the helm chart without reference data.  When I do, https://github.com/galaxyproject/galaxy-helm/blob/master/galaxy/templates/hook-cvmfs-fix.yaml this hook starts up and continues to wait for some cvmfs pods (ironically to kill them). As there is no pod, it runs indefinitely.

```
refdata.enabled: false
refdata.type: s3sci
s3csi.deploy: false
cvmfs.deploy: false
cvmfs.enabled: false
```

*Expected behaviour*:
If no cvmfs is used, then the pod for fixing cvmfs does not run. _Alternatively_ after no pod is found for 1-2 minutes, the pod finishes up.

Thank you!

### PR DESCRIPTION
**Pull request by ksuderman**
Removes the  template.  Ensure it is no longer needed before merging.  Mutually exlusive with #440.  Closes #439

### CODE REVIEW

**Comment by ksuderman** [comment]
Closing this since #440 was merged.

**Comment by nuwang** [comment]
I didn't realize this was made in parallel, but we will need to verify that things work without the fix, and then close or not?

**Comment by ksuderman** [comment]
Yeah, it was meant to be one or the other, but we can leave this open until we determine if the fix is still needed.

**Comment by nuwang** [comment]
No longer needed because it was fixed upstream.

**Pull request closed without merging**
